# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popupmovie.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Film(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(974, 334)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 120, 251, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(140, 30, 121, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(830, 210, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 270, 131, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.treeView = QtWidgets.QTreeView(Form)
        self.treeView.setGeometry(QtCore.QRect(270, 50, 541, 111))
        self.treeView.setObjectName("treeView")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(280, 20, 161, 16))
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 10, 141, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(640, 10, 141, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.treeView_2 = QtWidgets.QTreeView(Form)
        self.treeView_2.setGeometry(QtCore.QRect(10, 210, 801, 111))
        self.treeView_2.setObjectName("treeview2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 180, 161, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(470, 170, 141, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(640, 170, 141, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.timeEdit = QtWidgets.QTimeEdit(Form)
        self.timeEdit.setGeometry(QtCore.QRect(140, 50, 118, 22))
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Nom du film :"))
        self.label_3.setText(_translate("Form", "Description du film :"))
        self.label_5.setText(_translate("Form", "Durée :"))
        self.pushButton.setText(_translate("Form", "Sauvegarder"))
        self.pushButton_2.setText(_translate("Form", "Annuler"))
        self.label.setText(_translate("Form", "Liste de catégories :"))
        self.pushButton_3.setText(_translate("Form", "Ajouter une catégorie"))
        self.pushButton_4.setText(_translate("Form", "Supp. une catégorie"))
        self.label_8.setText(_translate("Form", "Liste d\'acteurs :"))
        self.pushButton_5.setText(_translate("Form", "Ajouter un acteur"))
        self.pushButton_6.setText(_translate("Form", "Supp. un acteur"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Film()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())