# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Connexion(object):
    def setupUi(self, Connexion):
        Connexion.setObjectName("Connexion")
        Connexion.resize(270, 122)
        self.buttonBox = QtWidgets.QDialogButtonBox(Connexion)
        self.buttonBox.setGeometry(QtCore.QRect(90, 80, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit_3 = QtWidgets.QLineEdit(Connexion)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 20, 161, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Connexion)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 50, 161, 20))
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(Connexion)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Connexion)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Connexion)
        self.buttonBox.accepted.connect(Connexion.accept)
        self.buttonBox.rejected.connect(Connexion.reject)
        QtCore.QMetaObject.connectSlotsByName(Connexion)

    def retranslateUi(self, Connexion):
        _translate = QtCore.QCoreApplication.translate
        Connexion.setWindowTitle(_translate("Connexion", "Connexion"))
        self.label.setText(_translate("Connexion", "Code employé :"))
        self.label_2.setText(_translate("Connexion", " Mot de passe :"))
